/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora;

/**
 *
 * @author Usuário
 */
public class FrameCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form FrameCalculadora
     */
    double num, operacao;
    int calculo;
    
    
    public FrameCalculadora() {
        initComponents();
       // btOn.setEnabled(false);
        desabilitarBotoes();  // chama o método para desabilitar todos os botões e vai iniciar a calculadora com todos os botoes desativados

    }
    
    
    public void operacaoAritimetica(){
        switch (calculo) {
            
            case 1: // adição
                    operacao =  num + Double.parseDouble(jTextField2.getText()); //convertendo String para Double para fazer o calculo 
                    jTextField1.setText(Double.toString(operacao)); // convertendo o resultado do calculo, contino na variavel operacao em String novamente para apresentar na tela do usuario  
                break;
                
            case 2: // subtração
                
                operacao =  num - Double.parseDouble(jTextField2.getText()); //convertendo String para Double    
                    jTextField1.setText(Double.toString(operacao));
                break;
             
            case 3: // multiplicação
                
                operacao = num * Double.parseDouble(jTextField2.getText());
                jTextField2.setText(Double.toString(operacao));
                break;
                
            case 4: // divisão
                
                operacao = num / Double.parseDouble(jTextField2.getText());
                jTextField2.setText(Double.toString(operacao));
                break;
                
        }
        
    
    }
    

    public void desabilitarBotoes() { // esse método vai desabilitar todos os botões
        jTextField2.setEnabled(false);
        jTextField2.setText("");  // aqui vai fazer com que seja limpado o visor no momento que desligar a calculadora 

        btZero.setEnabled(false);
        btUm.setEnabled(false);
        btDois.setEnabled(false);
        btTres.setEnabled(false);
        btQuatro.setEnabled(false);
        btCinco.setEnabled(false);
        btSeis.setEnabled(false);
        btSete.setEnabled(false);
        btOito.setEnabled(false);
        btNove.setEnabled(false);
        btSomar.setEnabled(false);
        btSubtrair.setEnabled(false);
        btDividir.setEnabled(false);
        btMultiplicar.setEnabled(false);
        btResultado.setEnabled(false);
        btPonto.setEnabled(false);
        btLimparVisor.setEnabled(false);
        btLimpar.setEnabled(false);

    }

    public void habilitarBotoes() { // esse método vai habiliatar todos os botões
        jTextField2.setEnabled(true);

        btZero.setEnabled(true);
        btUm.setEnabled(true);
        btDois.setEnabled(true);
        btTres.setEnabled(true);
        btQuatro.setEnabled(true);
        btCinco.setEnabled(true);
        btSeis.setEnabled(true);
        btSete.setEnabled(true);
        btOito.setEnabled(true);
        btNove.setEnabled(true);
        btSomar.setEnabled(true);
        btSubtrair.setEnabled(true);
        btDividir.setEnabled(true);
        btMultiplicar.setEnabled(true);
        btResultado.setEnabled(true);
        btPonto.setEnabled(true);
        btLimparVisor.setEnabled(true);
        btLimpar.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        btSete = new javax.swing.JButton();
        btOito = new javax.swing.JButton();
        btNove = new javax.swing.JButton();
        btQuatro = new javax.swing.JButton();
        btCinco = new javax.swing.JButton();
        btSeis = new javax.swing.JButton();
        btUm = new javax.swing.JButton();
        btDois = new javax.swing.JButton();
        btTres = new javax.swing.JButton();
        btDividir = new javax.swing.JButton();
        btMultiplicar = new javax.swing.JButton();
        btSubtrair = new javax.swing.JButton();
        btZero = new javax.swing.JButton();
        btResultado = new javax.swing.JButton();
        btSomar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btOn = new javax.swing.JRadioButton();
        btOff = new javax.swing.JRadioButton();
        btLimparVisor = new javax.swing.JButton();
        btPonto = new javax.swing.JButton();
        jlMostraOperacao = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton10.setText("0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setFocusCycleRoot(false);
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        btSete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSete.setText("7");
        btSete.setToolTipText("");
        btSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeteActionPerformed(evt);
            }
        });

        btOito.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btOito.setText("8");
        btOito.setToolTipText("");
        btOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOitoActionPerformed(evt);
            }
        });

        btNove.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btNove.setText("9");
        btNove.setToolTipText("");
        btNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNoveActionPerformed(evt);
            }
        });

        btQuatro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btQuatro.setText("4");
        btQuatro.setToolTipText("");
        btQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuatroActionPerformed(evt);
            }
        });

        btCinco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCinco.setText("5");
        btCinco.setToolTipText("");
        btCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCincoActionPerformed(evt);
            }
        });

        btSeis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSeis.setText("6");
        btSeis.setToolTipText("");
        btSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeisActionPerformed(evt);
            }
        });

        btUm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btUm.setText("1");
        btUm.setToolTipText("");
        btUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUmActionPerformed(evt);
            }
        });

        btDois.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDois.setText("2");
        btDois.setToolTipText("");
        btDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoisActionPerformed(evt);
            }
        });

        btTres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btTres.setText("3");
        btTres.setToolTipText("");
        btTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTresActionPerformed(evt);
            }
        });

        btDividir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDividir.setText("/");
        btDividir.setToolTipText("");
        btDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDividirActionPerformed(evt);
            }
        });

        btMultiplicar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btMultiplicar.setText("*");
        btMultiplicar.setToolTipText("");
        btMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultiplicarActionPerformed(evt);
            }
        });

        btSubtrair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSubtrair.setText("-");
        btSubtrair.setToolTipText("");
        btSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubtrairActionPerformed(evt);
            }
        });

        btZero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btZero.setText("0");
        btZero.setToolTipText("");
        btZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZeroActionPerformed(evt);
            }
        });

        btResultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btResultado.setText("=");
        btResultado.setToolTipText("");
        btResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResultadoActionPerformed(evt);
            }
        });

        btSomar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSomar.setText("+");
        btSomar.setToolTipText("");
        btSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSomarActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setToolTipText("");
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btLimpar.setText("<-");
        btLimpar.setMaximumSize(new java.awt.Dimension(32, 32));
        btLimpar.setMinimumSize(new java.awt.Dimension(32, 32));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        buttonGroup1.add(btOn);
        btOn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btOn.setText("ON");
        btOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOnActionPerformed(evt);
            }
        });

        buttonGroup1.add(btOff);
        btOff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btOff.setText("OFF");
        btOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOffActionPerformed(evt);
            }
        });

        btLimparVisor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btLimparVisor.setText("C");
        btLimparVisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparVisorActionPerformed(evt);
            }
        });

        btPonto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btPonto.setText(".");
        btPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPontoActionPerformed(evt);
            }
        });

        jlMostraOperacao.setForeground(new java.awt.Color(255, 0, 0));
        jlMostraOperacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlMostraOperacao.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btZero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btUm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btQuatro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btDois, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btTres, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btOito, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btNove, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jTextField2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btOn)
                                .addGap(80, 80, 80))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btOff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(btLimparVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlMostraOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlMostraOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btOn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btOff)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btLimparVisor)
                        .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btDividir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSete)
                    .addComponent(btOito)
                    .addComponent(btMultiplicar)
                    .addComponent(btNove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQuatro)
                    .addComponent(btCinco)
                    .addComponent(btSeis)
                    .addComponent(btSubtrair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btUm)
                            .addComponent(btDois)
                            .addComponent(btTres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btResultado)
                                .addComponent(btZero))
                            .addComponent(btPonto)))
                    .addComponent(btSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZeroActionPerformed
        // jTextField2.setText( "0"); // dessa forma, se eu digitar 0 e depois  digitar 1 vai ser apresentado sempreo ultimo valor digitado, para conseguir digitar ex (123) faço: 
        jTextField2.setText(jTextField2.getText() + "0");
    }//GEN-LAST:event_btZeroActionPerformed

    private void btResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResultadoActionPerformed
       operacaoAritimetica(); // aqui estou chamando o metodo de operacao aritmética, para que quando pressionar "=" seja realizado o calculo
       jlMostraOperacao.setText(""); // vai limpar o label quando limpar o visor 
               
    }//GEN-LAST:event_btResultadoActionPerformed

    private void btSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSomarActionPerformed
         // jTextField2.setText(jTextField2.getText() + "+"); vou remover esta opção pois vai ser utilizado um label para apresentar para o uauario e não o textFild. 
         //Esta opação faz ficar por o começo da conta na parte superior da calculadora, possibilitando digitar mais números para fazer a operação
         
         num = Double.parseDouble(jTextField2.getText()); // estou convertendo a entrada de dados para double
         calculo = 1; // declaração de troca de chamada. Aqui estou chaando o metodo calculo e passando que a opeção que vai ocorrer quando pressionar o botao "+" é o switch case 1 
         jTextField2.setText(""); // aqui estou limpando o textField
         jlMostraOperacao.setText(num + "+"); // aqui apresenta no label o primeiro numero informado e o sinal de +
    }//GEN-LAST:event_btSomarActionPerformed

    private void btUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUmActionPerformed
        //jTextField2.setText( "1");
        jTextField2.setText(jTextField2.getText() + "1"); // exibindo o numero atual e o sinal de +

    }//GEN-LAST:event_btUmActionPerformed

    private void btDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoisActionPerformed
        //jTextField2.setText( "2");
        jTextField2.setText(jTextField2.getText() + "2");
    }//GEN-LAST:event_btDoisActionPerformed

    private void btTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTresActionPerformed
        jTextField2.setText(jTextField2.getText() + "3");
    }//GEN-LAST:event_btTresActionPerformed

    private void btSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubtrairActionPerformed
        //jTextField2.setText(jTextField2.getText() + "-");
        
        num = Double.parseDouble(jTextField2.getText()); // estou convertendo a entrada de dados para double
         calculo = 2; // declaração de troca de chamada. Aqui estou chamando o metodo calculo e passando que a opeção que vai ocorrer quando pressionar o botao "-" é o switch case 2 
         jTextField2.setText(""); // aqui estou limpando o textField
         jlMostraOperacao.setText(num + "-"); // aqui apresenta no label o primeiro numero informado e o sinal de -
    }//GEN-LAST:event_btSubtrairActionPerformed

    private void btQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuatroActionPerformed
        jTextField2.setText(jTextField2.getText() + "4");
    }//GEN-LAST:event_btQuatroActionPerformed

    private void btCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCincoActionPerformed
        jTextField2.setText(jTextField2.getText() + "5");
    }//GEN-LAST:event_btCincoActionPerformed

    private void btSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeisActionPerformed
        jTextField2.setText(jTextField2.getText() + "6");
    }//GEN-LAST:event_btSeisActionPerformed

    private void btMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultiplicarActionPerformed
        //jTextField2.setText(jTextField2.getText() + "*");
        
        num = Double.parseDouble(jTextField2.getText()); // estou convertendo a entrada de dados para double
         calculo = 3; // declaração de troca de chamada. Aqui estou chamando o metodo calculo e passando que a opeção que vai ocorrer quando pressionar o botao "*" é o switch case 3 
         jTextField2.setText(""); // aqui estou limpando o textField
         jlMostraOperacao.setText(num + "*"); // aqui apresenta no label o primeiro numero informado e o sinal de *
    }//GEN-LAST:event_btMultiplicarActionPerformed

    private void btSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeteActionPerformed
        jTextField2.setText(jTextField2.getText() + "7");
    }//GEN-LAST:event_btSeteActionPerformed

    private void btOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOitoActionPerformed
        jTextField2.setText(jTextField2.getText() + "8");
    }//GEN-LAST:event_btOitoActionPerformed

    private void btNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNoveActionPerformed
        jTextField2.setText(jTextField2.getText() + "9");
    }//GEN-LAST:event_btNoveActionPerformed

    private void btDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDividirActionPerformed
        //jTextField2.setText(jTextField2.getText() + "/");
        
        num = Double.parseDouble(jTextField2.getText()); // estou convertendo a entrada de dados para double
         calculo = 4; // declaração de troca de chamada. Aqui estou chamando o metodo calculo e passando que a opeção que vai ocorrer quando pressionar o botao "/" é o switch case 4
         jTextField2.setText(""); // aqui estou limpando o textField
         jlMostraOperacao.setText(num + "/"); // aqui apresenta no label o primeiro numero informado e o sinal de /
    }//GEN-LAST:event_btDividirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        
        int length = jTextField2.getText().length();    // variavel usada para saber o comprimento da String através do método length
        int num = jTextField2.getText().length() -1; // nessa variavél vai pegar o satmanho da string e subtrair 1 
        String valorDigitado;
        
        if (length > 0) {
        
            StringBuilder apagar = new StringBuilder(jTextField2.getText()); //StringBuilder cria um construtor de strings vazio parar armazenar Strings
            apagar.deleteCharAt(num); // usado para deletar um unico caractere de uma posição expecífica
            valorDigitado= apagar.toString(); // convertendo novamente para String
            jTextField2.setText(valorDigitado); // o valor do campo de texto é armazenado na variavél "valorDigitado"
        }
    }//GEN-LAST:event_btLimparActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btLimparVisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparVisorActionPerformed
        jTextField2.setText(""); // aqui vai limpar o visor inteiro, então se digitar alguns numeros e quiser fazer uma novab conta, sí preciono o botão "C"
    }//GEN-LAST:event_btLimparVisorActionPerformed

    private void btPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPontoActionPerformed
        jTextField2.setText(jTextField2.getText() + ".");
    }//GEN-LAST:event_btPontoActionPerformed

    private void btOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOnActionPerformed
        habilitarBotoes(); // chama o método para habilitar todos os botões
    }//GEN-LAST:event_btOnActionPerformed

    private void btOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOffActionPerformed
        desabilitarBotoes(); // chama o método desabiliatarbotoes
    }//GEN-LAST:event_btOffActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCinco;
    private javax.swing.JButton btDividir;
    private javax.swing.JButton btDois;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btLimparVisor;
    private javax.swing.JButton btMultiplicar;
    private javax.swing.JButton btNove;
    private javax.swing.JRadioButton btOff;
    private javax.swing.JButton btOito;
    private javax.swing.JRadioButton btOn;
    private javax.swing.JButton btPonto;
    private javax.swing.JButton btQuatro;
    private javax.swing.JButton btResultado;
    private javax.swing.JButton btSeis;
    private javax.swing.JButton btSete;
    private javax.swing.JButton btSomar;
    private javax.swing.JButton btSubtrair;
    private javax.swing.JButton btTres;
    private javax.swing.JButton btUm;
    private javax.swing.JButton btZero;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jlMostraOperacao;
    // End of variables declaration//GEN-END:variables
}
