/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Usuário
 */
public class ViewMenu extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenu
     */
    public ViewMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmCadastroCliente = new javax.swing.JMenuItem();
        Produtos = new javax.swing.JMenu();
        jmCadastroProdutos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmCadastroVendas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jMenu1.setText("Clientes");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmCadastroCliente.setText("Cadastro");
        jmCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jmCadastroCliente);

        jMenuBar1.add(jMenu1);

        Produtos.setText("Produtos");

        jmCadastroProdutos.setText("Cadastro");
        jmCadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroProdutosActionPerformed(evt);
            }
        });
        Produtos.add(jmCadastroProdutos);

        jMenuBar1.add(Produtos);

        jMenu3.setText("Vendas");

        jmCadastroVendas.setText("Cadastro");
        jmCadastroVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroVendasActionPerformed(evt);
            }
        });
        jMenu3.add(jmCadastroVendas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatorios");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jmCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroClienteActionPerformed
        ViewCadastroCliente clientes = new ViewCadastroCliente();
        clientes.setVisible(true);
    }//GEN-LAST:event_jmCadastroClienteActionPerformed

    private void jmCadastroVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroVendasActionPerformed
        ViewCadastroVenda venda = new ViewCadastroVenda();
        venda.setVisible(true);
    }//GEN-LAST:event_jmCadastroVendasActionPerformed

    private void jmCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroProdutosActionPerformed
        ViewCadastroProduto produto = new ViewCadastroProduto();
        produto.setVisible(true);
    }//GEN-LAST:event_jmCadastroProdutosActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Produtos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmCadastroCliente;
    private javax.swing.JMenuItem jmCadastroProdutos;
    private javax.swing.JMenuItem jmCadastroVendas;
    // End of variables declaration//GEN-END:variables
}
